--[[
    DEFAULT CONFIGURATION FILE
    Do NOT edit this file, edit e_admin/lua/Configuration.lua
]]--

-- DO NOT EDIT THIS FILE
local Settings = {

Prefix = "!",
Command = {
    Categories = {},
},
Groups = {
    ["user"] = {
        Rank = 0,
        Perms = {".cmds.generic.user"},
        Default = true,
    },
    ["mod"] = {
        Rank = 100,
        Perms = {".cmds.generic.moderator"},
    },
    ["admin"] = {
        Rank = 200,
        Perms = {".cmds.generic.admin"},
    },
    ["superadmin"] = {
        Rank = 300,
        Perms = {".*"},
        Options = {
            Aquisition = "Administrator"
        }
    },
    ["owner"] = {
        Rank = 1000,
        Options = {
            Override = "Administrator",
            Aquisition = "Console",
        },
    }
}
}

if e_admin then
    e_admin.defConfig = Settings
end
